name: The Accompanist
favicon: null
layout_spectrum: 1
typography_spectrum: 0.52197
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#77becf'
    - '#a2654c'
    - '#ffffff'
    - '#034957'
    - '#5a260b'
  brandStrength: 0.1875
  lightness: 0.6875
  saturation: 0.1875
  rhythmicContrast: 1
purpose: []
