name: The Accompanist
favicon: null
layout_spectrum: 0.2508176751434803
typography_spectrum: 0.32157636899501085
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.8628939460031688
  lightness: 0.8963805441744626
  saturation: 0.9248654851689935
  rhythmicContrast: 0.3004718928132206
purpose: []
